# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(name: 'Admin', email: 'a@gmail.com', password: '123456', profession: "Software Engineer", admin:'true')
User.create(name: 'master', email: 'm@gmail.com', password: '123456', profession: "Software Engineer" )
User.create(name: 'marc', email: 'c@gmail.com', password: '123456', profession: "Software Engineer" )
User.create(name: 'stegen', email: 'd@gmail.com', password: '123456', profession: "Network Engineer", admin:'true' )
User.create(name: 'messi', email: 'e@gmail.com', password: '123456', profession: "Network Engineer", admin:'true' )
User.create(name: 'lionel', email: 'f@gmail.com', password: '123456', profession: "Network Engineer" )
User.create(name: 'cris', email: 'g@gmail.com', password: '123456', profession: "Maintenance Engineer" )
User.create(name: 'paul', email: 'h@gmail.com', password: '123456', profession: "Maintenance Engineer" )
User.create(name: 'meddy', email: 'i@gmail.com', password: '123456', profession: "Maintenance Engineer" )
User.create(name: 'mister', email: 'j@gmail.com', password: '123456', profession: "Education" )
User.create(name: 'lorris', email: 'k@gmail.com', password: '123456', profession: "Education" )
User.create(name: 'dele', email: 'l@gmail.com', password: '123456', profession: "Education" )
User.create(name: 'ali', email: 'm@gmail.com', password: '123456', profession: "Accountant" )
User.create(name: 'ya', email: 'n@gmail.com', password: '123456', profession: "Accountant" )
User.create(name: 'matty', email: 'o@gmail.com', password: '123456', profession: "Accountant" )
User.create(name: 'jam', email: 'p@gmail.com', password: '123456', profession: "Pastor" )
User.create(name: 'jane', email: 'q@gmail.com', password: '123456', profession: "Pastor" )
User.create(name: 'james', email: 'r@gmail.com', password: '123456', profession: "Pastor" )
User.create(name: 'luc', email: 's@gmail.com', password: '123456', profession: "Pastor" )
User.create(name: 'jean', email: 't@gmail.com', password: '123456', profession: "Network Engineer" )
User.create(name: 'yun', email: 'u@gmail.com', password: '123456', profession: "Network Engineer" )
User.create(name: 'fin', email: 'v@gmail.com', password: '123456', profession: "Network Engineer" )
Announcement.create(title: 'here', body:'We are a company that provides business and IT outsourcing services, and we take intense pride in helping companies handle their business operations. Due to expansion, we are looking to add to our team of software support engineers. As a customer-facing support engineer, your role will be to provide phone and email-based technical support to corporate customers while ensuring ticket resolution and customer satisfaction. ', owners: 'All', user_id: 1)
Announcement.create(title: 'here', body:'Working across a range of market-leading Microsoft and Microfocus technologies including Cloud, Security, Database, ERP and CRM systems the software support engineer will grow in knowledge through our extensive training programmes. All product training knowledge will be provided, and this learning continues through your career with onsite career development programmes that allow our to gain broad technical knowledge. ', owners: 'All', user_id: 3)